language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
  - hhvm
before_script:
  - composer install --prefer-dist
script:
  - composer test
after_success:
  - '[ "$TRAVIS_PHP_VERSION" == "7.1" ] && vendor/bin/coveralls'
dist: trusty
